var alias = {
  exists: 'exists',
  access: 'access',
  utimes: 'utimes',
  futimes: 'futimes',
  fsync: 'fsync',
  readdir: 'readdir',
  mkdir: 'mkdir',
  rmdir: 'rmdir',
  unlink: 'unlink',
  realpath: 'realpath',
  readlink: 'readlink',
  symlink: 'symlink',
  link: 'link',
  stat: 'stat',
  fstat: 'fstat',
  lstat: 'lstat',
  lchmod: 'lchmod',
  fchmod: 'fchmod',
  chmod: 'chmod',
  lchown: 'lchown',
  fchown: 'fchown',
  chown: 'chown',
  truncate: 'truncate',
  ftruncate: 'ftruncate',
  rename: 'rename',
  open: 'open',
  close: 'close',
  writeFile: 'writeFile',
  appendFile: 'appendFile',
  // alias as stream are preferred
  read: 'fdread',
  write: 'fdwrite',
}

module.exports = alias;
