#!/usr/bin/env node

var commands = require('./commands')
  , async = require('async')
  , exec = require('child_process').exec
  , spawn = require('child_process').spawn
  , revert = require('ttycolor').defaults();

var list = Object.keys(commands)
  , delimiter
    = '----------------------------------------'
    + '----------------------------------------';

async.mapSeries(list, function(nm, cb) {
  var item = commands[nm]
    , cmd = item.cmd
    , args
    , opts = {stdio: 'inherit'};

  console.log(delimiter);
  console.log(nm + ': %s', cmd);
  console.log(delimiter);

  if(item.spawn) {
    cmd = cmd.split(/\s+/);
    args = cmd.slice(1);
    cmd = cmd[0];
    var ps = spawn(cmd, args, opts);
    ps.once('close', function() {
      cb();
    });
  }else{
    exec(cmd, function(err, stdout, stderr) {
      if(stdout) {
        process.stdout.write(stdout);
      }
      cb(err, cmd);
    })
  }
}, function(err, results) {
  if(err) {
    console.error(err);
    process.exit(1);
  }
})
