#!/usr/bin/env node

var husk = require('..').core().exec()
  .plugin([
    require('husk-argv'),
    require('husk-concat'),
    require('husk-buffer'),
    require('husk-lines'),
    require('husk-each'),
    require('husk-filter'),
    require('husk-transform'),
    require('husk-stringify')
  ]);

husk(process.argv.slice(2))
  .argv()
  //.cd('lib')
  //.find()
  //.buffer()
  //.lines()
  //.each()
  //.filter(function(){return /\.md$/.test(this)})
  //.transform(function(){return [this]})
  //.concat()
  .stringify({indent: 2})
  .print()
  .run();
