#!/usr/bin/env node

var husk = require('..')
  .plugin([
    require('husk-transform'),
    require('husk-stringify')
  ]);

husk(process.env)
  .transform(function(){return {editor: this.EDITOR}})
  .stringify({indent: 2})
  .print()
  .run();
