#!/usr/bin/env node

var husk = require('..').core().exec();

husk()
  .whoami(console.log.bind(null, '[code: %s, signal: %s]'))
  .once('end', function(){console.log('[end] whoami')})
  .print()
  .run();
