#!/usr/bin/env node

var husk = require('..').core()
  .plugin([
    require('husk-fs')
  ]);

var buffer = require('buffer-flow');

husk()
  .read('package.json')
  .pipe(buffer())
  .print().run();
