#!/usr/bin/env node

var husk = require('..').core().exec().fs()
  .plugin([
    require('husk-buffer'),
    require('husk-parse'),
    require('husk-filter'),
    require('husk-pluck'),
    require('husk-transform'),
    require('husk-stringify'),
  ]);

var input = 'package.json'
  , output = 'dependencies.json';

husk(input)
  .read()
  .buffer()
  // rewrite file path
  .through(function(){this.path = output})
  // parse as json and assign
  .parse(function(){return this.body}, {field: 'body'})
  // perform transformation
  .transform(function() {
    var body = this.body;
    for(var k in body.dependencies) {
      body.dependencies[k] = '~2.0.0';
    }
    return this;
  })
  // back to string for write
  .stringify(
    function(){return this.body.dependencies}, {indent: 2, field: 'output'})
  .write(function(){return this.output})
  .run(function() {
    // print file contents (debug)
    husk(output)
      .read()
      .buffer()
      .pluck(function(){return this.body})
      .print()
      // clean up file, demo only
      .unlink(output)
      .run();
  });
