#!/usr/bin/env node

var path = require('path')
  , husk = require('..').core().exec().fs()
  .plugin([
    require('husk-pluck'),
    require('husk-transform'),
  ]);

var name = path.basename(__filename) + '-example.log'
  , content = 'file content';

husk(name)
  //.touch(name)
  .open('w')
  .pluck(1)
  .async(function write(fd, cb) {
    //console.log('got fd: %s', fd);
    var h = husk(fd)
      .fwrite(content)
      .transform(function(){return fd;})
      .close()
      .on('finish', cb)
      //.on('finish', function(){console.log('finish after close')})
      .run();
  })
  //.cat(name)
  .print(function(){console.log('final print');console.dir(arguments)})
  .run();
