#!/usr/bin/env node

var path = require('path')
  , husk = require('..').core().exec().fs()
  .plugin([
    require('husk-pluck'),
    require('husk-buffer'),
    require('husk-transform'),
  ]);

var name = path.basename(__filename) + '-example.log'
  , content = '[file content]';

husk(name)
  .open('w')
  .pluck(1)
  .async(function writer(cb) {
    var fd = this.valueOf();
    var h = husk(fd)
      // write to fd is aliased write() -> fdwrite()
      .fdwrite(fd, content)
      .close(fd)
      .run(cb);
  })
  // re-read and print file to verify write
  .cat(name)
  .print(console.log)
  // clean up file
  .unlink(name)
  .run();
