#!/usr/bin/env node

var husk = require('../')
  .plugin([
    require('husk-exec')
  ]);

husk()
  .exec('ls')
  .exec('cat', console.log.bind(null, '[code: %s, signal: %s]'))
  .pipe(process.stdout)
