#!/usr/bin/env node

var husk = require('..').core().exec();

husk()
  .ls()
  // pipe `ls` stdout to `cat` stdin
  .pipe(1)
  .cat(console.log.bind(null, '[code: %s, signal: %s]'))
  .print()
  .run();
