#!/usr/bin/env node

var husk = require('..').defaults();
husk()
  .exec('ls')
  // pipe `ls` stdout to `cat` stdin
  .pipe(1)
  .exec('cat', console.log.bind(null, '[code: %s, signal: %s]'))
  .print()
  .run(true);
