#!/usr/bin/env node

var husk = require('..').exec()
  .plugin([
    require('husk-argv'),
    require('husk-io'),
    require('husk-concat'),
    require('husk-lines'),
    require('husk-each'),
    require('husk-transform'),
    require('husk-stringify')
  ]);

husk()
  .find('doc/readme')
  .lines()
  .concat()
  .each()
  .file()
  .debug()
  //.stat(function(){return [this.valueOf()]})
  //.transform(function(){return [{size: this.size}]})
  //.concat()
  .stringify({indent: 2})
  //.print()
  .run();
