#!/usr/bin/env node

var husk = require('..').core()
  , exec = require('husk-exec')
  , print = require('husk-print')
  , concat = require('husk-concat')
  , buffer =  require('husk-buffer')
  , lines = require('husk-lines')
  , filter = require('husk-filter')
  , transform = require('husk-transform')
  , stringify = require('husk-stringify');

var h = husk();
h
  .pipe(exec('find', ['lib']))
    .on('end', console.log.bind(null, '[end] find'))
  .pipe(buffer())
    .on('end', console.log.bind(null, '[end] buffer'))
  .pipe(lines())
    .on('end', console.log.bind(null, '[end] lines'))
  .pipe(filter(function(){return /\.md$/.test(this)}))
    .on('end', console.log.bind(null, '[end] filter'))
  .pipe(transform(function(){return [this]}))
    .on('end', console.log.bind(null, '[end] transform'))
  .pipe(concat())
    .on('end', console.log.bind(null, '[end] concat'))
  .pipe(stringify({indent: 2}))
    .on('end', console.log.bind(null, '[end] stringify'))
  .pipe(print(function noop(){}))
    .on('finish', console.log.bind(null, '[finish] print'));

h.run();
