#!/usr/bin/env node

var husk = require('..').core().fs()
  .plugin([
    require('husk-buffer'),
    require('husk-parse'),
    require('husk-pluck'),
    require('husk-stringify'),
  ]);

husk()
  .read('package.json')
  .buffer()
  .parse()
  .pluck(function(){return this.dependencies})
  .stringify({indent: 2})
  .print()
  .run();
