#!/usr/bin/env node

var husk = require('..').core().exec()
  .plugin([
    require('husk-concat'),
    require('husk-buffer'),
    require('husk-lines'),
    require('husk-each'),
    require('husk-filter'),
    require('husk-transform'),
    require('husk-stringify')
  ]);

function onEnd() {
  console.log('' + this);
}

husk()
  .cd('lib')
  .find()
    .on('end', onEnd)
  .buffer()
    .on('end', onEnd)
  .lines()
    .on('end', onEnd)
  .each()
    .on('end', onEnd)
  .filter(function(){return /\.md$/.test(this)})
    .on('end', onEnd)
  .transform(function(){return [this]})
    .on('end', onEnd)
  .concat()
    .on('end', onEnd)
  .stringify({indent: 2})
    .on('end', onEnd)
  .print(function noop(){})
    .on('finish', onEnd)
  .run();
