#!/usr/bin/env node

var husk = require('..').core().exec()
  .plugin([
    require('husk-concat'),
    require('husk-buffer'),
    require('husk-lines'),
    require('husk-each'),
    require('husk-filter'),
    require('husk-transform'),
    require('husk-stringify')
  ]);

function onEnd(phase) {
  console.log('[end] %s', phase);
}

husk()
  .cd('lib')
  .find()
    .on('end', onEnd.bind(null, 'find'))
  .buffer()
    .on('end', onEnd.bind(null, 'buffer'))
  .lines()
    .on('end', onEnd.bind(null, 'lines'))
  .each()
    .on('end', onEnd.bind(null, 'each'))
  .filter(function(){return /\.md$/.test(this)})
    .on('end', onEnd.bind(null, 'filter'))
  .transform(function(){return [this]})
    .on('end', onEnd.bind(null, 'transform'))
  .concat()
    .on('end', onEnd.bind(null, 'concat'))
  .stringify({indent: 2})
    .on('end', onEnd.bind(null, 'stringify'))
  .print(function noop(){})
    .on('finish', onEnd.bind(null, 'print'))
  .run();
