#!/usr/bin/env node

var husk = require('..').exec()
  .plugin([
    // force terminal for sbin/ebin execution
    {plugin: require('husk-prompt'), conf: {terminal: true}},
    require('husk-wait')
  ]);

husk('lib')
  // auto fill prompt so it can be automated
  .wait(
    {
      output: 'prompt ⚡ choose directory: (lib)',
      input: 'doc'
    }
  )
  .prompt({terminal: true}, function(ps, chunk, encoding, cb) {
    ps.prompt(
      {
        message: 'choose directory:',
        default: 'lib'
      },
      function complete(err, val) {
        ps.close();
        cb(err, val ? val[0] : null);
      })
  })
  .find(function(){return [this.valueOf()]})
  .print()
  .run();
