#!/usr/bin/env node

var husk = require('../')
  .plugin([
    require('husk-exec')
  ]);

husk()
  .exec('pwd'/* , function(){console.log(arguments)}*/)
  //.on('error', function(err) {
    //console.error(err);
    //process.exit(1);
  //})
  .pipe(process.stdout)
