#!/usr/bin/env node

var husk = require('..').core()
  .plugin([
    require('husk-lines'),
    require('husk-split'),
    require('husk-object'),
    require('husk-pluck'),
    require('husk-stringify')
  ]);

husk()
  .stdin()
  .lines()
  .split()
  .object({schema: {user: 0, line: 1, when: -2}})
  .pluck(0)
  .stringify({indent: 2})
  .print().run();
