#!/usr/bin/env node

var husk = require('..').core()
  , exec = require('husk-exec')
  , print = require('husk-print')
  , concat = require('husk-concat')
  , buffer =  require('husk-buffer')
  , lines = require('husk-lines')
  , filter = require('husk-filter')
  , transform = require('husk-transform')
  , stringify = require('husk-stringify');

function onEnd(phase) {
  console.log('[end] %s', phase)
}

var h = husk();
h
  .pipe(exec('find', ['lib']))
    .on('end', onEnd.bind(null, 'find'))
  .pipe(buffer())
    .on('end', onEnd.bind(null, 'buffer'))
  .pipe(lines())
    .on('end', onEnd.bind(null, 'lines'))
  .pipe(filter(function(){return /\.md$/.test(this)}))
    .on('end', onEnd.bind(null, 'filter'))
  .pipe(transform(function(){return [this]}))
    .on('end', onEnd.bind(null, 'transform'))
  .pipe(concat())
    .on('end', onEnd.bind(null, 'concat'))
  .pipe(stringify({indent: 2}))
    .on('end', onEnd.bind(null, 'stringify'))
  .pipe(print(function noop(){}))
    .on('finish', onEnd.bind(null, 'print'))

h.run();
