#!/usr/bin/env node

var husk = require('../')
  .plugin([
    require('husk-stdin'),
    require('husk-lines'),
    require('husk-split'),
    require('husk-object'),
    require('husk-stringify')
  ]);

husk()
  .lines()
  .split()
  .object({schema: {user: 0, line: 1, when: -2}})
  .stringify({indent: 2})
  .print()
  .run();
