#!/usr/bin/env node

var husk = require('../');

husk.plugin([
  require('husk-lines'),
  require('husk-split'),
  require('husk-object'),
  require('husk-stringify'),
]);

//console.dir('who : ' + husk.plugin);

var h = husk();
var n = h.stdin()
  .lines()
  .split()
  .object({schema: {user: 0, line: 1, when: -2}})
  .stringify({indent: 2})
  .pipe(process.stdout);
